name: First Workflow

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4

    - name: setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
  
    - name: Run version node
      run: node --version