name: github-action-condition



#------------Trigger Workflow-----------------------
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'releases/**'
    # paths:
    #   - '**.js'
  workflow_run:
    workflow: [Run workflow python script] 
    types:
      - success
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test  # Correction ici








#--------------Condition contains()------------------OK
# name: github-action-condition
# run-name: ${{ github.actor }} - Condition github action

# on:
#   push:
#   pull_request:
#   workflow_dispatch:
    
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: contains(fromJSON('["push", "pull_request"]'), github.event_name)
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20"

#       - name: Install dependencies
#         run: npm install

#       - name: Run build
#         run: npm run build

#   test:
#     runs-on: ubuntu-latest
#     if: contains(fromJSON('["push", "pull_request"]'), github.event_name)
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20"
      
#       - name: Install dependencies
#         run: npm install

#       - name: Run test
#         run: npm run test

#   deploy:
#     runs-on: ubuntu-latest
#     if: (contains(fromJSON('["push"]'), github.event_name) && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: npm install

#       - name: Run deploy
#         run: npm run deploy

#       - name: Run deploy confirmation
#         if: success()
#         run: echo "Deploy successfully completed"
