name: first-workflow
run-name: ${{ github.actor}} is learning github-action
on: [push] # trigger qui declenche le workflow githun-action sur all-branch
jobs: # travaux à faire
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats  
      - run: bats -V
 
      

