name: build and test github action
run-name: ${{ github.actor}} 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependances
        run: npm install

      - name: Run build
        run: npm run build
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v4

  #     - name: setup nodejs
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
      
  #     - name: Run Test
  #       run: npm run test
        
  # steps:
  #  runs-on: ubuntu-latest            