# name: Destroy EC2 with Terraform

# # Ce workflow peut être déclenché manuellement via l'interface GitHub Actions
# on:
#   workflow_dispatch:

# jobs:
#   terraform-destroy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout the code
#       uses: actions/checkout@v2

#     - name: Install Terraform
#       uses: hashicorp/setup-terraform@v2
#       with:
#         terraform_version: 1.5.0

#     - name: Terraform Init
#       run: terraform init

#     - name: Terraform Destroy
#       run: terraform destroy -auto-approve
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
