name: Destroy EC2 with Terraform
run-name: ${{ github.actor}} - Destroy EC2 with Terraform

on:
  workflow_dispatch:  # Ce déclencheur permet d'exécuter manuellement le workflow depuis l'interface GitHub Actions

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan (destroy)
      run: terraform plan -destroy -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
